version: '3.8'
services:
    database:
        image: postgres:14-alpine
        container_name: db_postgres
        volumes:
            - ./postgres-scripts:/docker-entrypoint-initdb.d
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: db_pokemons
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
    backend:
        image: pokemon-image
        build:
          dockerfile: ./Dockerfile
        restart: on-failure
        depends_on:
            - database